test_run:
  image: python:3.6-buster
  before_script:
    - apt-get update
    - pip3 install cython
    - pip3 install pyBigWig
    - pip3 install SIRVsuite --extra-index-url=https://test.pypi.org/simple/
  script:
    - python -m tests.unitTest -v
  when: manual
  